### PR TITLE
Runlocally (addresses issue #4)

### PR DESCRIPTION
**Pull request by koudyk**
Main changes:
- added 1 cell at the start of tutorial.ipynb to check if the data is available to the notebook, and if not, to download it from OSF. 
- added instructions to README.md for running the tutorial locally
- updated requirements.txt so the notebook can be run in a virtual environment. 
  - @tsalo and @ltetrel  I suspect this will make the binder notebooks take longer to run because there will be more requirements to download. Let me know if you want me to make a separate requirements file for running the notebook locally
  - I couldn't keep the version requirement for matplotlib for some reason. I upgraded pip, but maybe pip hasn't been updated since the new matplotlib version came out... not sure how important this is.

### CODE REVIEW

**Comment by tsalo** [comment]
This looks good to me. I think the initial build may take longer but we'll want to do that at least an hour or two before the tutorial anyway. 

> I couldn't keep the version requirement for matplotlib for some reason. I upgraded pip, but maybe pip hasn't been updated since the new matplotlib version came out... not sure how important this is.

I don't think it's important. I only pinned to the versions I had locally.

**Comment by ltetrel** [comment]
If we want to be consistent across time with the environment, it is better to version all the libraries inside `requirements.txt`.
You don't want to re-build your environment in the future and face issues.
=> If you don't plan to have a long term support for this, this is totally fine.

**Comment by ltetrel** [comment]
Regarding the data download, and if you want it to be consistent with the `binder/data_req.json` (and Neurolibre pipeline), you can call repo2data also in the first cell.
This will makes the first cell shorter, and the data provenance and dest fully tracked on one file (`binder/data_req.json`) instead of "hard-coding" the provenance and dest in the first cell.
Instead of osfclient dependency you could install repo2data (which includes osfclient).

**Comment by koudyk** [comment]
Re requirements:
@tsalo, do you want to have it work long term? If so, I can add versions to the requirements file. 

Re data:
To be honest, I just did it in the first way that I figured out. I didn't realize repo2data was a python package. Do you think I should change it at this point? It seems to be working.

**Comment by tsalo** [comment]
@koudyk I pinned the packages in 7c86d4c and used a `~=` for matplotlib so I think that should be sufficient.

If the code works as-is, I'm fine using `osfclient` directly, but I'd be happy to replace it with `repo2data` after the course is over.

**Comment by ltetrel** [comment]
@koudyk yes no worry let's leave it. @tsalo Just make sure that if you change the `data_req.json`, change also the first notebook cell. Another advantage of repo2data is that you don't need to check if the folder exists or not, and it checks if the data already exists so the instructions for downloading the data would really be a one-liner: `repo2data -r data_req.json`

**Pull request merged**
